# Generated by Django 2.2.12 on 2020-04-15 19:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок рассылки')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст письма')),
                ('attachments', models.FileField(upload_to='mailing_attachments', verbose_name='Вложения')),
            ],
            options={
                'verbose_name': 'Список рассылки',
                'verbose_name_plural': 'Списки рассылки',
            },
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
