# Generated by Django 3.0.5 on 2020-04-17 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20200415_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='attachments',
            field=models.FileField(blank=True, upload_to='mailing_attachments', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
